### PR TITLE
Don't send method returns replies when caller doesn't want them

### PR DESCRIPTION
**Pull request by michallowasrzechonek-silvair**

### CODE REVIEW

**Comment by acrisci** [comment]
What's the actual issue you're running into here?

**Comment by michallowasrzechonek-silvair** [comment]
On some systems AppArmor and DBus spam system log with errors about message delivery failures

**Comment by acrisci** [comment]
Oh ok sounds legitimate. Since the spec says "*should* not send a reply", I want to keep an override a possibility with manual sending which I think is still possible.

Do you want to write a test for it?

**Comment by michallowasrzechonek-silvair** [comment]
Sure, I'll add it to the PR

**Comment by acrisci** [comment]
:+1:

**Comment by michallowasrzechonek-silvair** [comment]
Hey, I wanted to add tests!

**Comment by acrisci** [comment]
Go ahead. I won't release without them.

**Pull request merged**
